config/routes.rb
Rails.application.routes.draw do
  root "sasaerus#new"
  resources :sasaerus
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sasaeru.rb
class Sasaeru < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sasaerus_controller.rb
class SasaerusController < ApplicationController
  before_action :set_sasaeru, only: [:show, :edit, :update, :destroy]

  # GET /sasaerus
  # GET /sasaerus.json
  def index
    if params[:spell] == "開けごま"
      @sasaerus = Sasaeru.all
    else
      redirect_to root_path
    end
  end

  # GET /sasaerus/1
  # GET /sasaerus/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf { send_pdf(@sasaeru) }
      # format.png { send_png(@sasaeru) }
    end
  end

  # GET /sasaerus/new
  def new
    @sasaeru = Sasaeru.new
  end

  # GET /sasaerus/1/edit
  def edit
  end

  # POST /sasaerus
  # POST /sasaerus.json
  def create
    @sasaeru = Sasaeru.new(sasaeru_params)

    respond_to do |format|
      if @sasaeru.save
        format.html { redirect_to @sasaeru, notice: 'Sasaeru was successfully created.' }
        format.json { render :show, status: :created, location: @sasaeru }
      else
        format.html { render :new }
        format.json { render json: @sasaeru.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sasaerus/1
  # PATCH/PUT /sasaerus/1.json
  def update
    respond_to do |format|
      if @sasaeru.update(sasaeru_params)
        format.html { redirect_to @sasaeru, notice: 'Sasaeru was successfully updated.' }
        format.json { render :show, status: :ok, location: @sasaeru }
      else
        format.html { render :edit }
        format.json { render json: @sasaeru.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sasaerus/1
  # DELETE /sasaerus/1.json
  def destroy
    @sasaeru.destroy
    respond_to do |format|
      format.html { redirect_to sasaerus_url, notice: 'Sasaeru was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sasaeru
      @sasaeru = Sasaeru.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sasaeru_params
      params.require(:sasaeru).permit(:top_text, :title, :sub_title, :author, :base_color, :lead, :sub_lead_1, :sub_lead_2, :sub_lead_3, :sub_lead_4, :bottom_text, :publisher)
    end

    def send_pdf(sasaeru)
      send_data(generate_sasaeru_theme(sasaeru),
                filename: "sasaeru.pdf",
                type: "application/pdf",
                disposition: "attachment")
    end

    # def send_png(sasaeru)
    #   pdf = MiniMagick::Image.open(send_pdf(sasaeru))
    #
    #   MiniMagick::Tool::Convert.new do |convert|
    #     convert << pdf.pages.first.path
    #     convert << "png:8sasaeru.png"
    #     png = convert
    #   end
    #
    #   send_data(png,
    #             filename: "sasaeru.png",
    #             type: "image/png",
    #             disposition: "attachment")
    # end

    def generate_sasaeru_theme(sasaeru)
      file = File.join(Rails.root, "app", "assets", "reports", "sasaeru.tlf")
      report = Thinreports::Report.new layout: file

      report.start_new_page

      report.page.item(:top_text).value(sasaeru.top_text)
      report.page.item(:title).value(sasaeru.title)
      report.page.item(:sub_title).value(sasaeru.sub_title)
      report.page.item(:sub_title_background).style(:fill_color, sasaeru.base_color)

      report.page.item(:author).value(sasaeru.author)

      report.page.item(:lead).value(sasaeru.lead)
      report.page.item(:lead).style(:color, sasaeru.base_color)
      report.page.item(:sub_lead_1).value(sasaeru.sub_lead_1)
      report.page.item(:sub_lead_2).value(sasaeru.sub_lead_2)
      report.page.item(:sub_lead_3).value(sasaeru.sub_lead_3)
      report.page.item(:sub_lead_4).value(sasaeru.sub_lead_4)

      report.page.item(:bottom_text).value(sasaeru.bottom_text)
      report.page.item(:publisher).value(sasaeru.publisher)

      report.generate
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/application/_header.html.erb
<header class="row mb-3 ml-2">
  <div class="col-md-8 mx-auto">
    <h1>〇〇を支える技術ジェネレーター</h1>
  </div>
  <div class="col-md-2">
    <%= link_to "https://github.com/matt-note/sasaeru_generator" do %>
      <%= image_tag("github.png", size: "42x42", class: "d-block github-link mt-2 ml-5") %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>〇〇を支える技術ジェネレーター</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "favicon" %>
  </head>

  <body class="mt-3">
    <div class="container">
      <%= render "header" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/sasaerus/_form.html.erb
<%= form_with(model: sasaeru, local: true, class: "ml-4") do |form| %>
  <% if sasaeru.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sasaeru.errors.count, "error") %> prohibited this sasaeru from being saved:</h2>

      <ul>
      <% sasaeru.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :top_text, class: "col-lg-3 col-form-label"%>
    <div class="col-lg-9">
      <%= form.text_field :top_text, size: 30, value: @sasaeru.top_text, class: "form-control shadow-none" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :title, class: "col-lg-3 col-form-label" %>
    <div class="col-lg-9">
      <%= form.text_field :title, size: 30, value: @sasaeru.title, class: "form-control shadow-none" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :sub_title, class: "col-lg-3 col-form-label" %>
    <div class="col-lg-9">
      <%= form.text_field :sub_title, size: 30, value: @sasaeru.sub_title, class: "form-control shadow-none" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :author, class: "col-lg-3 col-form-label" %>
    <div class="col-lg-9">
      <%= form.text_field :author, size: 30, value: @sasaeru.author, class: "form-control shadow-none" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :base_color, class: "col-lg-3 col-form-label" %>
    <div class="col-lg-9 mt-1">
      <%= form.color_field :base_color, value: @sasaeru.base_color %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :lead, class: "col-lg-3 col-form-label" %>
    <div class="col-lg-9">
      <%= form.text_area :lead, rows: 2, cols: 30, value: @sasaeru.lead, class: "form-control shadow-none" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :sub_lead_1, class: "col-lg-3 col-form-label" %>
    <div class="col-lg-9">
      <%= form.text_field :sub_lead_1, size: 30, value: @sasaeru.sub_lead_1, class: "form-control shadow-none" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :sub_lead_2, class: "col-lg-3 col-form-label" %>
    <div class="col-lg-9">
      <%= form.text_field :sub_lead_2, size: 30, value: @sasaeru.sub_lead_2, class: "form-control shadow-none" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :sub_lead_3, class: "col-lg-3 col-form-label" %>
    <div class="col-lg-9">
      <%= form.text_field :sub_lead_3, size: 30, value: @sasaeru.sub_lead_3, class: "form-control shadow-none" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :sub_lead_4, class: "col-lg-3 col-form-label" %>
    <div class="col-lg-9">
      <%= form.text_field :sub_lead_4, size: 30, value: @sasaeru.sub_lead_4, class: "form-control shadow-none" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :bottom_text, class: "col-lg-3 col-form-label" %>
    <div class="col-lg-9">
      <%= form.text_field :bottom_text, size: 30, value: @sasaeru.bottom_text, class: "form-control shadow-none" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :publisher, class: "col-lg-3 col-form-label" %>
    <div class="col-lg-9">
      <%= form.text_field :publisher, size: 30, value: @sasaeru.publisher, class: "form-control shadow-none" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary text-white" %>
  </div>
<% end %>

app/views/sasaerus/edit.html.erb
<div class="row justify-content-center">
  <div class="col-lg-5">
    <%= render 'form', sasaeru: @sasaeru %>
  </div>

  <div class="col-lg-5 ml-1">
    <%= image_tag "sasaeru.jpg", width: "470px" %>
  </div>
</div>

app/views/sasaerus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sasaerus</h1>

<table>
  <thead>
    <tr>
      <th>Top text</th>
      <th>Title</th>
      <th>Sub title</th>
      <th>Author</th>
      <th>Base color</th>
      <th>Lead</th>
      <th>Sub lead 1</th>
      <th>Sub lead 2</th>
      <th>Sub lead 3</th>
      <th>Sub lead 4</th>
      <th>Bottom text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sasaerus.each do |sasaeru| %>
      <tr>
        <td><%= sasaeru.top_text %></td>
        <td><%= sasaeru.title %></td>
        <td><%= sasaeru.sub_title %></td>
        <td><%= sasaeru.author %></td>
        <td><%= sasaeru.base_color %></td>
        <td><%= sasaeru.lead %></td>
        <td><%= sasaeru.sub_lead_1 %></td>
        <td><%= sasaeru.sub_lead_2 %></td>
        <td><%= sasaeru.sub_lead_3 %></td>
        <td><%= sasaeru.sub_lead_4 %></td>
        <td><%= sasaeru.bottom_text %></td>
        <td><%= link_to 'Show', sasaeru %></td>
        <td><%= link_to 'Edit', edit_sasaeru_path(sasaeru) %></td>
        <td><%= link_to 'Destroy', sasaeru, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sasaeru', new_sasaeru_path %>

app/views/sasaerus/new.html.erb
<div class="row justify-content-center">
  <div class="col-lg-5">
    <%= render 'form', sasaeru: @sasaeru %>
  </div>

  <div class="col-lg-5 ml-1">
    <%= image_tag "sasaeru.jpg", width: "470px" %>
  </div>
</div>

app/views/sasaerus/show.html.erb
<div class="col-lg-10 mx-auto">
  <div class="ml-3">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>一番上の文字:</strong>
      <%= @sasaeru.top_text %>
    </p>

    <p>
      <strong>タイトル:</strong>
      <%= @sasaeru.title %>
    </p>

    <p>
      <strong>サブタイトル:</strong>
      <%= @sasaeru.sub_title %>
    </p>

    <p>
      <strong>著者名:</strong>
      <%= @sasaeru.author %>
    </p>

    <p>
      <strong>カラー:</strong>
      <%= @sasaeru.base_color %>
    </p>

    <p>
      <strong>リード文:</strong>
      <%= @sasaeru.lead %>
    </p>

    <p>
      <strong>サブリード文1:</strong>
      <%= @sasaeru.sub_lead_1 %>
    </p>

    <p>
      <strong>サブリード文2:</strong>
      <%= @sasaeru.sub_lead_2 %>
    </p>

    <p>
      <strong>サブリード文3:</strong>
      <%= @sasaeru.sub_lead_3 %>
    </p>

    <p>
      <strong>サブリード文4:</strong>
      <%= @sasaeru.sub_lead_4 %>
    </p>

    <p>
      <strong>ボトムテキスト:</strong>
      <%= @sasaeru.bottom_text %>
    </p>

    <p>
      <strong>出版社名:</strong>
      <%= @sasaeru.publisher %>
    </p>


    <hr>

    <%= link_to "PDFでダウンロードする", sasaeru_path(@sasaeru, format: "pdf"), class: "btn btn-success text-white" %>

    <%= link_to '作り直す', edit_sasaeru_path(@sasaeru), class: "btn btn-info text-white" %>
  </div>
</div>